### ISSUE TITLE
Conflicts with r-sf

### ISSUE THREAD

**Issue by halldc** [conda-forge/r-rpostgres-feedstock#10] opened 2020-01-27 18:01 UTC
**Issue:** I'm unable to install the latest versions of `r-base`, `r-rpostgres` and `r-sf` simultaneously. 

I'm unable to interpret the conflict messages though (see below). They don't align with my expectations (e.g. there are r36 builds of r-bit64 found [here](https://anaconda.org/conda-forge/r-bit64/files)).

@conda-forge/r 

```
$ conda install r-base==3.6.2 r-rpostgres==1.2.0 r-sf==0.8.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libopenblas conflicts for:
r-rpostgres==1.2.0 -> r-base[version='>=3.5,<3.6.0a0'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0']
r-base==3.6.2 -> libblas[version='>=3.8.0,<4.0a0'] -> libopenblas[version='>=0.3.6,<0.3.7.0a0|>=0.3.7,<0.3.8.0a0|>=0.3.7,<1.0a0|>=0.3.6,<1.0a0']

Package r-base conflicts for:
r-rpostgres==1.2.0 -> r-bit64 -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5.1,<3.5.2.0a0|>=3.5.0,<3.5.1.0a0|>=3.4.3,<3.4.4.0a0|>=3.4.2,<3.4.3a0']
r-rpostgres==1.2.0 -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-sf==0.8.0 -> r-classint[version='>=0.2_1'] -> r-base[version='3.2.0.*|3.2.1.*|3.2.2.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5,<3.6.0a0|>=3.5.1,<3.5.2.0a0|>=3.5.0,<3.5.1.0a0|>=3.4.3,<3.4.4.0a0|>=3.4.2,<3.4.3a0|3.3.1.*']
r-sf==0.8.0 -> r-base[version='>=3.6,<3.7.0a0']
r-base==3.6.2

Package zstd conflicts for:
r-sf==0.8.0 -> libgdal[version='>=3.0.1,<3.1.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0|>=1.4.4,<1.4.5.0a0']
r-base==3.6.2 -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0|>=1.4.3,<1.4.4.0a0|>=1.4.4,<1.4.5.0a0']

Package r-rcpp conflicts for:
r-sf==0.8.0 -> r-rcpp
r-rpostgres==1.2.0 -> r-rcpp[version='>=0.11.4.2']
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/david.hall/miniconda3/envs/test2:
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test2
    active env location : /Users/david.hall/miniconda3/envs/test2
            shell level : 2
       user config file : /Users/david.hall/.condarc
 populated config files : /Users/david.hall/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.8.1.final.0
       virtual packages : __osx=10.15.2
       base environment : /Users/david.hall/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/david.hall/miniconda3/pkgs
                          /Users/david.hall/.conda/pkgs
       envs directories : /Users/david.hall/miniconda3/envs
                          /Users/david.hall/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.8.1 Darwin/19.2.0 OSX/10.15.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by dpryan79** [comment] 2020-01-27 22:44
It seems the issue is due to proj4, which has historically been quite a pain to get built.

**Comment by fhoehle** [comment] 2020-02-01 06:16
@halldc ~I'm unable to reproduce the issue using the conda-forge docker image~
the `r-sf` dependencies include not the latest `libgdal=3.0.1=h61e1f9c_8` (latest would be `libgdal=3.0.4`) introducing in its dependencies `libpq=11.5`. This contradicts latest `r-rpostgres`, 1.2.0, which requires `libpq >=12.1,<13.0a0`. Therefore an updated build of `r-sf` requiring a newer `libgdal>=3.0.2` is needed to solve the conflict.

**Comment by fhoehle** [comment] 2020-02-02 20:20
@halldc using latest `r-sf=0.8.1` an environment providing latest `r-sf`, `r-base` and `r-rpostgres` is available.
`docker run -it condaforge/linux-anvil-comp7 conda create -n test r-base=3.6.2 r-rpostgres=1.2.0 r-sf=0.8.1`
Therefore I will close this issue.

**Closed as completed by fhoehle** 2020-02-02 20:20 UTC

**Comment by halldc** [comment] 2020-02-03 17:58
Ah yes, it seems to work with the latest version (`r-sf==0.8.1`). Thanks for your help!
